name: action-agent

description: Run Codex CLI for issue/issue_comment threads.

inputs:
  model:
    description: Codex model override (optional)
    required: false
    default: ""
  reasoning_effort:
    description: Codex reasoning effort override (optional)
    required: false
    default: ""
  openai_api_key:
    description: OpenAI API key
    required: true
  github_token:
    description: GitHub token used for API + gh
    required: true

runs:
  using: node20
  main: dist/index.js
