name: action-agent

description: Run Codex CLI for issue/issue_comment threads.

inputs:
  model:
    description: Codex model override (optional)
    required: false
    default: ""
  reasoning_effort:
    description: Codex reasoning effort override (optional)
    required: false
    default: ""
  prompt:
    description: Optional extra instructions for the agent
    required: false
    default: ""
  persistence:
    description: Enable session persistence across runs
    required: false
  api_key:
    description: Model provider API key
    required: true
  github_token:
    description: GitHub token used for API + gh
    required: true

runs:
  using: node20
  main: dist/index.js
